"""initial schema

Revision ID: 976a014c5fac
Revises: 
Create Date: 2026-09-21 22:34:48.114585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976a014c5fac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('time_uploaded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artworks_id'), 'artworks', ['id'], unique=False)
    op.create_table('similar_artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('similarity_score', sa.Integer(), nullable=False),
    sa.Column('is_similar', sa.Boolean(), nullable=False),
    sa.Column('time_scanned', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artwork_id', 'url', name='uq_artwork_url')
    )
    op.create_index(op.f('ix_similar_artworks_id'), 'similar_artworks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similar_artworks_id'), table_name='similar_artworks')
    op.drop_table('similar_artworks')
    op.drop_index(op.f('ix_artworks_id'), table_name='artworks')
    op.drop_table('artworks')
    # ### end Alembic commands ###
